/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_Permission */

#ifndef _Included_io_github_Permission
#define _Included_io_github_Permission
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_Permission
 * Method:    permission
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_Permission_permission
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
