/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_vmBoy_Who */

#ifndef _Included_io_github_vmBoy_Who
#define _Included_io_github_vmBoy_Who
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_vmBoy_Who
 * Method:    map
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_io_github_vmBoy_Who_map
        (JNIEnv *, jclass, jint);

/*
 * Class:     io_github_vmBoy_Who
 * Method:    unlink
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_github_vmBoy_Who_unlink
        (JNIEnv *, jclass, jstring);

/*
 * Class:     io_github_vmBoy_Who
 * Method:    permission
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_io_github_vmBoy_Who_permission
        (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
